spring:
  application:
    name: WalletAPI

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  kafka:
    bootstrap-servers: 172.21.123.22:9092
    consumer:
      group-id: WalletAPI

wallet:
  sync:
    delay: PT10M
  app:
    token: ${WALLET_APP_TOKEN}
