package in.pinnacle.apps.wallet.api.util.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * DTO class which represents wallet entity in consumer application
 *
 * @author Saivarma Akarapu
 */
@Data
@NoArgsConstructor
public class WalletDTO implements Serializable {

    /**
     * Serial version UID for serialization and deserialization
     */
    @Serial
    private static final long serialVersionUID = 938188764288853868L;

    /**
     * Unique identifier of the wallet master which will be generated by table
     */
    private Long walletId;

    /**
     * USER ID which this wallet belongs to
     */
    @NotNull
    private Long userId;

    /**
     * Currency of the amount which this wallet holds
     */
    @NotBlank
    private String currency;

    /**
     * Type of the wallet probably pre-paid or post paid
     */
    @NotBlank
    private String walletType;

    /**
     * Amount that was available in this wallet
     */
    private BigDecimal balance;

    /**
     * Status of the wallet to know whether it is active or not
     */
    private Boolean isActive;

    /**
     * Date at which the wallet was created
     */
    private LocalDateTime createdAt;

    public WalletDTO(Long walletId, BigDecimal balance) {
        this.walletId = walletId;
        this.balance = balance;
    }

}
